# ### タスクを追加
POST http://localhost:8080/tasks
Content-Type: application/json  

  {
      "title": "streak test",
      "dueDate": "23:59",   
      "user": {
          "userId": 1 
      }
  }
{
    "title": "deleteTask test",
    "dueDate": "2025-06-01T23:59:00",
    "user": {
        "userId": 1
    }
}

### タスク取得
GET http://localhost:8080/tasks/6


### タスク更新（title変更 → createdAtも更新されることを確認）
PUT http://localhost:8080/tasks/1
Content-Type: application/json

{
  "taskId": 1,
  "title": "新しいタイトル",
  "dueDate": "2025-06-01T23:59:00",
  "user": {
    "userId": 1
  }
}

### タイトル変更なし（createdAtは変更されないはず）
PUT http://localhost:8080/tasks/1
Content-Type: application/json

{
  "taskId": 1,
  "title": "元のタイトル",
  "dueDate": "2025-06-05T23:59:00",
  "user": {
    "userId": 1
  }
}

### ユーザー登録 (userId は自動生成)
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "securepassword",
  "confirmPassword": "securepassword"
}

### タスクの削除

DELETE http://localhost:8080/tasks/6
Content-Type: application/json


### タスク完了状態の切り替え
PUT http://localhost:8080/tasks/1/toggle
Content-Type: application/

### ユーザーのタスクステータスを更新
POST http://localhost:8080/tasks/user/1/updateStreak
Content-Type: application/json
